version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
